# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yury Kozhenov
email: yurykozhenov@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi! My name is Yury Kozhenov and I am Full Stack Web Developer.
  I am language agnostic programmer, but I'm in love with Python <3.
  Feel free to explore my site, dear guest!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yurykozhenov.github.io/" # the base hostname & protocol for your site
twitter_username: yurykozhenov
github_username:  yurykozhenov

# Build settings
markdown: kramdown
